In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Health data.csv')

In [3]:
df.head(20)

,ID,City_Code,Region_Code,Accomodation_Type,Reco_Insurance_Type,Upper_Age,Lower_Age,Is_Spouse,Health Indicator,Holding_Policy_Duration,Holding_Policy_Type,Reco_Policy_Cat,Reco_Policy_Premium,Response
0,1,C3,3213,Rented,Individual,36,36,No,X1,14+,3.0,22,11628.0,0
1,2,C5,1117,Owned,Joint,75,22,No,X2,NaN,NaN,22,30510.0,0
2,3,C5,3732,Owned,Individual,32,32,No,NaN,1.0,1.0,19,7450.0,1
3,4,C24,4378,Owned,Joint,52,48,No,X1,14+,3.0,19,17780.0,0
4,5,C8,2190,Rented,Individual,44,44,No,X2,3.0,1.0,16,10404.0,0
5,6,C9,1785,Rented,Individual,52,52,No,X2,5.0,1.0,22,15264.0,1
6,7,C3,679,Owned,Individual,28,28,No,NaN,NaN,NaN,17,10640.0,0
7,8,C1,3175,Owned,Joint,75,73,Yes,X4,9.0,4.0,17,29344.0,1
8,9,C15,3497,Owned,Joint,52,43,No,X1,14.0,3.0,1,27283.2,0
9,10,C1,530,Owned,Joint,59,26,Yes,NaN,7.0,4.0,18,21100.8,1
10,11,C28,600,Owned,Individual,21,21,No,X2,NaN,NaN,21,4068.0,1
11,12,C27,1097,Owned,Joint,59,47,Yes,X3,3.0,3.0,13,25043.2,0
12,13,C7,3453,Owned,Individual,66,66,No,NaN,1.0,2.0,20,17192.0,1
13,14,C5,900,Rented,Individual,20,20,No,X2,NaN,NaN,18,8364.0,0
14,15,C20,1911,Rented,Individual,27,27,No,X3,2.0,3.0,9,9440.0,0
15,16,C3,1484,Rented,Individual,20,20,No,X3,NaN,NaN,2,4912.0,0
16,17,C3,1090,Owned,Individual,34,34,No,X1,11.0,1.0,20,6660.0,0
17,18,C7,677,Owned,Individual,43,43,No,X2,NaN,NaN,19,10386.0,0
18,19,C1,1634,Owned,Individual,55,55,No,X2,1.0,3.0,21,12580.0,0
19,20,C20,973,Owned,Individual,27,27,No,NaN,NaN,NaN,4,8050.0,0

In [4]:
df.drop_duplicates()

,ID,City_Code,Region_Code,Accomodation_Type,Reco_Insurance_Type,Upper_Age,Lower_Age,Is_Spouse,Health Indicator,Holding_Policy_Duration,Holding_Policy_Type,Reco_Policy_Cat,Reco_Policy_Premium,Response
0,1,C3,3213,Rented,Individual,36,36,No,X1,14+,3.0,22,11628.0,0
1,2,C5,1117,Owned,Joint,75,22,No,X2,NaN,NaN,22,30510.0,0
2,3,C5,3732,Owned,Individual,32,32,No,NaN,1.0,1.0,19,7450.0,1
3,4,C24,4378,Owned,Joint,52,48,No,X1,14+,3.0,19,17780.0,0
4,5,C8,2190,Rented,Individual,44,44,No,X2,3.0,1.0,16,10404.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50877,50878,C4,845,Rented,Individual,22,22,No,X3,NaN,NaN,18,7704.0,0
50878,50879,C5,4188,Rented,Individual,27,27,No,X3,7.0,3.0,4,5408.0,0
50879,50880,C1,442,Rented,Individual,63,63,No,X2,14+,1.0,12,11374.0,0
50880,50881,C1,4,Owned,Joint,71,49,No,X2,2.0,2.0,16,28179.2,1
50881,50882,C3,3866,Rented,Individual,24,24,No,X3,2.0,3.0,18,11424.0,0

In [5]:
df.head(20)

,ID,City_Code,Region_Code,Accomodation_Type,Reco_Insurance_Type,Upper_Age,Lower_Age,Is_Spouse,Health Indicator,Holding_Policy_Duration,Holding_Policy_Type,Reco_Policy_Cat,Reco_Policy_Premium,Response
0,1,C3,3213,Rented,Individual,36,36,No,X1,14+,3.0,22,11628.0,0
1,2,C5,1117,Owned,Joint,75,22,No,X2,NaN,NaN,22,30510.0,0
2,3,C5,3732,Owned,Individual,32,32,No,NaN,1.0,1.0,19,7450.0,1
3,4,C24,4378,Owned,Joint,52,48,No,X1,14+,3.0,19,17780.0,0
4,5,C8,2190,Rented,Individual,44,44,No,X2,3.0,1.0,16,10404.0,0
5,6,C9,1785,Rented,Individual,52,52,No,X2,5.0,1.0,22,15264.0,1
6,7,C3,679,Owned,Individual,28,28,No,NaN,NaN,NaN,17,10640.0,0
7,8,C1,3175,Owned,Joint,75,73,Yes,X4,9.0,4.0,17,29344.0,1
8,9,C15,3497,Owned,Joint,52,43,No,X1,14.0,3.0,1,27283.2,0
9,10,C1,530,Owned,Joint,59,26,Yes,NaN,7.0,4.0,18,21100.8,1
10,11,C28,600,Owned,Individual,21,21,No,X2,NaN,NaN,21,4068.0,1
11,12,C27,1097,Owned,Joint,59,47,Yes,X3,3.0,3.0,13,25043.2,0
12,13,C7,3453,Owned,Individual,66,66,No,NaN,1.0,2.0,20,17192.0,1
13,14,C5,900,Rented,Individual,20,20,No,X2,NaN,NaN,18,8364.0,0
14,15,C20,1911,Rented,Individual,27,27,No,X3,2.0,3.0,9,9440.0,0
15,16,C3,1484,Rented,Individual,20,20,No,X3,NaN,NaN,2,4912.0,0
16,17,C3,1090,Owned,Individual,34,34,No,X1,11.0,1.0,20,6660.0,0
17,18,C7,677,Owned,Individual,43,43,No,X2,NaN,NaN,19,10386.0,0
18,19,C1,1634,Owned,Individual,55,55,No,X2,1.0,3.0,21,12580.0,0
19,20,C20,973,Owned,Individual,27,27,No,NaN,NaN,NaN,4,8050.0,0

In [6]:
df.isnull().sum()

ID                             0
City_Code                      0
Region_Code                    0
Accomodation_Type              0
Reco_Insurance_Type            0
Upper_Age                      0
Lower_Age                      0
Is_Spouse                      0
Health Indicator           11691
Holding_Policy_Duration    20251
Holding_Policy_Type        20251
Reco_Policy_Cat                0
Reco_Policy_Premium            0
Response                       0
dtype: int64

In [7]:
# Replace 14+ with 14.0 and ensured all values are floats
# errors='coerce' will turn any other strings to NaN temporarily

In [8]:
df['Holding_Policy_Duration'] = df['Holding_Policy_Duration'].replace('14+', 14.0)
df['Holding_Policy_Duration'] = pd.to_numeric(df['Holding_Policy_Duration'], errors='coerce')

In [9]:
df.head(20)

,ID,City_Code,Region_Code,Accomodation_Type,Reco_Insurance_Type,Upper_Age,Lower_Age,Is_Spouse,Health Indicator,Holding_Policy_Duration,Holding_Policy_Type,Reco_Policy_Cat,Reco_Policy_Premium,Response
0,1,C3,3213,Rented,Individual,36,36,No,X1,14.0,3.0,22,11628.0,0
1,2,C5,1117,Owned,Joint,75,22,No,X2,NaN,NaN,22,30510.0,0
2,3,C5,3732,Owned,Individual,32,32,No,NaN,1.0,1.0,19,7450.0,1
3,4,C24,4378,Owned,Joint,52,48,No,X1,14.0,3.0,19,17780.0,0
4,5,C8,2190,Rented,Individual,44,44,No,X2,3.0,1.0,16,10404.0,0
5,6,C9,1785,Rented,Individual,52,52,No,X2,5.0,1.0,22,15264.0,1
6,7,C3,679,Owned,Individual,28,28,No,NaN,NaN,NaN,17,10640.0,0
7,8,C1,3175,Owned,Joint,75,73,Yes,X4,9.0,4.0,17,29344.0,1
8,9,C15,3497,Owned,Joint,52,43,No,X1,14.0,3.0,1,27283.2,0
9,10,C1,530,Owned,Joint,59,26,Yes,NaN,7.0,4.0,18,21100.8,1
10,11,C28,600,Owned,Individual,21,21,No,X2,NaN,NaN,21,4068.0,1
11,12,C27,1097,Owned,Joint,59,47,Yes,X3,3.0,3.0,13,25043.2,0
12,13,C7,3453,Owned,Individual,66,66,No,NaN,1.0,2.0,20,17192.0,1
13,14,C5,900,Rented,Individual,20,20,No,X2,NaN,NaN,18,8364.0,0
14,15,C20,1911,Rented,Individual,27,27,No,X3,2.0,3.0,9,9440.0,0
15,16,C3,1484,Rented,Individual,20,20,No,X3,NaN,NaN,2,4912.0,0
16,17,C3,1090,Owned,Individual,34,34,No,X1,11.0,1.0,20,6660.0,0
17,18,C7,677,Owned,Individual,43,43,No,X2,NaN,NaN,19,10386.0,0
18,19,C1,1634,Owned,Individual,55,55,No,X2,1.0,3.0,21,12580.0,0
19,20,C20,973,Owned,Individual,27,27,No,NaN,NaN,NaN,4,8050.0,0

In [10]:
print(df['Holding_Policy_Duration'].isna().sum())

20251

In [11]:
print(df['Holding_Policy_Duration'].dtype)

float64

In [12]:
# check to see if NaN values mostly occur when policy type is also missing
print(df[df['Holding_Policy_Duration'].isna()]
    ['Holding_Policy_Type'].value_counts(dropna=False))

Holding_Policy_Type
NaN    20251
Name: count, dtype: int64

In [13]:
# Drop the ID column (it's unique to each row and won't help the model learn)
df.drop('ID', axis=1, inplace=True)

# fill Duration with 0 and Type with a placeholder (0.0)
df['Holding_Policy_Duration'] = df['Holding_Policy_Duration'].fillna(0)
df['Holding_Policy_Type'] = df['Holding_Policy_Type'].fillna(0.0)

# Handle 'Health Indicator' missing values
# Since it's categorical (X1, X2, etc.), we fill with the most frequent value (Mode)
health_mode = df['Health Indicator'].mode()[0]
df['Health Indicator'] = df['Health Indicator'].fillna(health_mode)

# Convert Binary Strings to 0 and 1
# This makes the data readable for mathematical models
binary_mapping = {'Yes': 1, 'No': 0, 'Owned': 1, 'Rented': 0, 'Individual': 1, 'Joint': 0}

df['Is_Spouse'] = df['Is_Spouse'].map(binary_mapping)
df['Accomodation_Type'] = df['Accomodation_Type'].map(binary_mapping)
df['Reco_Insurance_Type'] = df['Reco_Insurance_Type'].map(binary_mapping)

# results
print(df.isnull().sum())
print(df.head(20))

City_Code                  0
Region_Code                0
Accomodation_Type          0
Reco_Insurance_Type        0
Upper_Age                  0
Lower_Age                  0
Is_Spouse                  0
Health Indicator           0
Holding_Policy_Duration    0
Holding_Policy_Type        0
Reco_Policy_Cat            0
Reco_Policy_Premium        0
Response                   0
dtype: int64
   City_Code  Region_Code  Accomodation_Type  Reco_Insurance_Type  Upper_Age  \
0         C3         3213                  0                    1         36
1         C5         1117                  1                    0         75
2         C5         3732                  1                    1         32
3        C24         4378                  1                    0         52
4         C8         2190                  0                    1         44
5         C9         1785                  0                    1         52
6         C3          679                  1                    1         28
7         C1         3175                  1                    0         75
8        C15         3497                  1                    0         52
9         C1          530                  1                    0         59
10       C28          600                  1                    1         21
11       C27         1097                  1                    0         59
12        C7         3453                  1                    1         66
13        C5          900                  0                    1         20
14       C20         1911                  0                    1         27
15        C3         1484                  0                    1         20
16        C3         1090                  1                    1         34
17        C7          677                  1                    1         43
18        C1         1634                  1                    1         55
19       C20          973                  1                    1         27

    Lower_Age  Is_Spouse Health Indicator  Holding_Policy_Duration  \
0          36          0               X1                     14.0
1          22          0               X2                      0.0
2          32          0               X1                      1.0
3          48          0               X1                     14.0
4          44          0               X2                      3.0
5          52          0               X2                      5.0
6          28          0               X1                      0.0
7          73          1               X4                      9.0
8          43          0               X1                     14.0
9          26          1               X1                      7.0
10         21          0               X2                      0.0
11         47          1               X3                      3.0
12         66          0               X1                      1.0
13         20          0               X2                      0.0
14         27          0               X3                      2.0
15         20          0               X3                      0.0
16         34          0               X1                     11.0
17         43          0               X2                      0.0
18         55          0               X2                      1.0
19         27          0               X1                      0.0

    Holding_Policy_Type  Reco_Policy_Cat  Reco_Policy_Premium  Response
0                   3.0               22              11628.0         0
1                   0.0               22              30510.0         0
2                   1.0               19               7450.0         1
3                   3.0               19              17780.0         0
4                   1.0               16              10404.0         0
5                   1.0               22              15264.0         1
6                   0.0               17              10640.0         0
7                   4.0               17              29344.0         1
8                   3.0                1              27283.2         0
9                   4.0               18              21100.8         1
10                  0.0               21               4068.0         1
11                  3.0               13              25043.2         0
12                  2.0               20              17192.0         1
13                  0.0               18               8364.0         0
14                  3.0                9               9440.0         0
15                  0.0                2               4912.0         0
16                  1.0               20               6660.0         0
17                  0.0               19              10386.0         0
18                  3.0               21              12580.0         0
19                  0.0                4               8050.0         0

In [14]:
# One-Hot Encoding for remaining categorical columns
# We use drop_first=True to avoid the 'dummy variable trap' (multi-collinearity)
df_final = pd.get_dummies(df, columns=['City_Code', 'Health Indicator'], drop_first=True)

# Final check of the data types and shape
print(f"Original shape: {df.shape}")
print(f"New shape after encoding: {df_final.shape}")
print(df_final.head(20))

Original shape: (50882, 13)
New shape after encoding: (50882, 54)
    Region_Code  Accomodation_Type  Reco_Insurance_Type  Upper_Age  Lower_Age  \
0          3213                  0                    1         36         36
1          1117                  1                    0         75         22
2          3732                  1                    1         32         32
3          4378                  1                    0         52         48
4          2190                  0                    1         44         44
5          1785                  0                    1         52         52
6           679                  1                    1         28         28
7          3175                  1                    0         75         73
8          3497                  1                    0         52         43
9           530                  1                    0         59         26
10          600                  1                    1         21         21
11         1097                  1                    0         59         47
12         3453                  1                    1         66         66
13          900                  0                    1         20         20
14         1911                  0                    1         27         27
15         1484                  0                    1         20         20
16         1090                  1                    1         34         34
17          677                  1                    1         43         43
18         1634                  1                    1         55         55
19          973                  1                    1         27         27

    Is_Spouse  Holding_Policy_Duration  Holding_Policy_Type  Reco_Policy_Cat  \
0           0                     14.0                  3.0               22
1           0                      0.0                  0.0               22
2           0                      1.0                  1.0               19
3           0                     14.0                  3.0               19
4           0                      3.0                  1.0               16
5           0                      5.0                  1.0               22
6           0                      0.0                  0.0               17
7           1                      9.0                  4.0               17
8           0                     14.0                  3.0                1
9           1                      7.0                  4.0               18
10          0                      0.0                  0.0               21
11          1                      3.0                  3.0               13
12          0                      1.0                  2.0               20
13          0                      0.0                  0.0               18
14          0                      2.0                  3.0                9
15          0                      0.0                  0.0                2
16          0                     11.0                  1.0               20
17          0                      0.0                  0.0               19
18          0                      1.0                  3.0               21
19          0                      0.0                  0.0                4

    Reco_Policy_Premium  ...  City_Code_C8  City_Code_C9  Health Indicator_X2  \
0               11628.0  ...         False         False                False
1               30510.0  ...         False         False                 True
2                7450.0  ...         False         False                False
3               17780.0  ...         False         False                False
4               10404.0  ...          True         False                 True
5               15264.0  ...         False          True                 True
6               10640.0  ...         False         False                False
7               29344.0  ...         False         False                False
8               27283.2  ...         False         False                False
9               21100.8  ...         False         False                False
10               4068.0  ...         False         False                 True
11              25043.2  ...         False         False                False
12              17192.0  ...         False         False                False
13               8364.0  ...         False         False                 True
14               9440.0  ...         False         False                False
15               4912.0  ...         False         False                False
16               6660.0  ...         False         False                False
17              10386.0  ...         False         False                 True
18              12580.0  ...         False         False                 True
19               8050.0  ...         False         False                False

    Health Indicator_X3  Health Indicator_X4  Health Indicator_X5  \
0                 False                False                False
1                 False                False                False
2                 False                False                False
3                 False                False                False
4                 False                False                False
5                 False                False                False
6                 False                False                False
7                 False                 True                False
8                 False                False                False
9                 False                False                False
10                False                False                False
11                 True                False                False
12                False                False                False
13                False                False                False
14                 True                False                False
15                 True                False                False
16                False                False                False
17                False                False                False
18                False                False                False
19                False                False                False

    Health Indicator_X6  Health Indicator_X7  Health Indicator_X8  \
0                 False                False                False
1                 False                False                False
2                 False                False                False
3                 False                False                False
4                 False                False                False
5                 False                False                False
6                 False                False                False
7                 False                False                False
8                 False                False                False
9                 False                False                False
10                False                False                False
11                False                False                False
12                False                False                False
13                False                False                False
14                False                False                False
15                False                False                False
16                False                False                False
17                False                False                False
18                False                False                False
19                False                False                False

    Health Indicator_X9
0                 False
1                 False
2                 False
3                 False
4                 False
5                 False
6                 False
7                 False
8                 False
9                 False
10                False
11                False
12                False
13                False
14                False
15                False
16                False
17                False
18                False
19                False

[20 rows x 54 columns]